### ISSUE TITLE
what is use of 'as' inside columns array

### ISSUE THREAD

**Issue by deepak458** [emayskiy/Datatables-SSP-MultiTables#1]
@emayskiy this script is so much help me, but right now im stuckup on one this there is `$columns` array, inside `$columns` array there is a key `'as' => 'field3', 'as' => 'field4'...`.

So what is use of this value inside Datatable class ?

**Comment by emayskiy** [comment]
This is the alias of the field in the resulting query.
Example Query: 
```
SELECT 
    mt.id as main_table_id,  // - as from $columns
    jt.id as join_table_id 
FROM main_table as mt       // - as from $table
    LEFT JOIN join1_table_name as jt
    ON mt_id = jt.main_id   // - join_on from $table
```
