### ISSUE TITLE
Count and GroupBy Only Featuer into for official ssp.class.php

### ISSUE THREAD

**Issue by deepak458** [emayskiy/Datatables-SSP-MultiTables#5]
@emayskiy can you also add only count, Group By, Having feature for offical [ssp.class.php](https://github.com/DataTables/DataTables/blob/156faa83386460c578e00c460eca9766e38a0c5f/examples/server_side/scripts/ssp.class.php).

**Comment by emayskiy** [comment]
Unfortunately, I do not have enough free time now. But you can try to do it.

**Comment by deepak458** [comment]
@emayskiy i just build that file but i stuck up on one thing my **SQL** query is
```
"SELECT `CommentID`, `ClientID`, count(`ClientID`) AS `total`, `Status`, `description`, `start_date`, `salary` FROM `demo` "
```

I think every thing is ok but when i run this query error show 

```
Query Failed You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CommentID``) FROM `demo`' at line 1
```

**Comment by deepak458** [comment]
@but when i run i direct to query it work so what is issue.
