### ISSUE TITLE
Indefinido index

### ISSUE THREAD

**Issue by jpetercastillo** [emayskiy/Datatables-SSP-MultiTables#8]
Cuando se llamaba al archivo salía: indefinido index en los datos enviados.
Algunas funciones lo he definido como static, además que si no se envía alguna información se usó: isset() para verificar.
Confirmar si es correcto. Gracias.
[ssp.class.zip](https://github.com/emayskiy/Datatables-SSP-MultiTables/files/7100315/ssp.class.zip)

**Comment by emayskiy** [comment]
Confirm
